/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import ApplicationSystem.ApplicationSystem;
import UI.AmbulanceLogin.AmbulanceLoginJFrame;
import UI.DiagnosticsLogin.DiagnosticsLoginJFrame;
import UI.HospitalLogin.HospitalLoginJFrame;
import UI.PharmacyLogin.PharmacyLoginJFrame;
import User.UserAccount;
import javax.swing.JOptionPane;

/**
 *
 * @author Diksha
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    ApplicationSystem applicationSystem;
    UserAccount userAccount;
    public MainJFrame() {
        initComponents();
        this.setVisible(true);
        
        
        this.applicationSystem = ApplicationSystem.getInstance();
        //System.out.println("Main Frame"+this.applicationSystem.getHospitalUserAccountDirectory().getHospitaluseraccountlist().size());

    }
    
    public MainJFrame(ApplicationSystem applicationSystem, UserAccount userAccount){
        initComponents();
        this.setVisible(true);
        
        this.applicationSystem = applicationSystem;
        
        this.userAccount = userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        userNameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        logInBtn = new javax.swing.JButton();
        ambulanceBtn = new javax.swing.JButton();
        diagnosticsBtn = new javax.swing.JButton();
        hospitalBtn = new javax.swing.JButton();
        pharmacyBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jButton8.setBackground(new java.awt.Color(61, 118, 125));
        jButton8.setFont(new java.awt.Font("Kailasa", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Hospital");
        jButton8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/icons8-hospital-100 (2).png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 110, 110));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/icons8-medicine1-100.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, 80));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("MEDILINK");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 290, 70));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/icons8-hospital-100.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 120, 150));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/icons8-ambulance-102.png"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/icons8-driver-102.png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/icons8-pharma-102.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/icons8-nurse-100.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.setPreferredSize(new java.awt.Dimension(840, 540));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userNameField.setBackground(new java.awt.Color(0, 153, 153));
        userNameField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        userNameField.setForeground(new java.awt.Color(255, 255, 255));
        userNameField.setText("  Username");
        userNameField.setBorder(new javax.swing.border.MatteBorder(null));
        userNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameFieldActionPerformed(evt);
            }
        });
        jPanel3.add(userNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 210, 41));

        passwordField.setBackground(new java.awt.Color(0, 153, 153));
        passwordField.setForeground(new java.awt.Color(255, 255, 255));
        passwordField.setText("  Password");
        passwordField.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 210, 41));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 230, -1));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 313, 230, 10));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/icons8-user-40.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 40, -1));

        logInBtn.setBackground(new java.awt.Color(0, 153, 153));
        logInBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logInBtn.setForeground(new java.awt.Color(255, 255, 255));
        logInBtn.setText("Log In");
        logInBtn.setBorder(new javax.swing.border.MatteBorder(null));
        logInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInBtnActionPerformed(evt);
            }
        });
        jPanel3.add(logInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 100, 30));

        ambulanceBtn.setBackground(new java.awt.Color(0, 153, 153));
        ambulanceBtn.setFont(new java.awt.Font("Kailasa", 1, 14)); // NOI18N
        ambulanceBtn.setForeground(new java.awt.Color(255, 255, 255));
        ambulanceBtn.setText("Ambulance");
        ambulanceBtn.setBorder(new javax.swing.border.MatteBorder(null));
        ambulanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambulanceBtnActionPerformed(evt);
            }
        });
        jPanel3.add(ambulanceBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 160, 30));

        diagnosticsBtn.setBackground(new java.awt.Color(0, 153, 153));
        diagnosticsBtn.setFont(new java.awt.Font("Kailasa", 1, 14)); // NOI18N
        diagnosticsBtn.setForeground(new java.awt.Color(255, 255, 255));
        diagnosticsBtn.setText("Diagnostics");
        diagnosticsBtn.setBorder(new javax.swing.border.MatteBorder(null));
        diagnosticsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagnosticsBtnActionPerformed(evt);
            }
        });
        jPanel3.add(diagnosticsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 160, 30));

        hospitalBtn.setBackground(new java.awt.Color(0, 153, 153));
        hospitalBtn.setFont(new java.awt.Font("Kailasa", 1, 14)); // NOI18N
        hospitalBtn.setForeground(new java.awt.Color(255, 255, 255));
        hospitalBtn.setText("Hospital");
        hospitalBtn.setBorder(new javax.swing.border.MatteBorder(null));
        hospitalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalBtnActionPerformed(evt);
            }
        });
        jPanel3.add(hospitalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 160, 30));

        pharmacyBtn.setBackground(new java.awt.Color(0, 153, 153));
        pharmacyBtn.setFont(new java.awt.Font("Kailasa", 1, 14)); // NOI18N
        pharmacyBtn.setForeground(new java.awt.Color(255, 255, 255));
        pharmacyBtn.setText("Pharmacy");
        pharmacyBtn.setBorder(new javax.swing.border.MatteBorder(null));
        pharmacyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pharmacyBtnActionPerformed(evt);
            }
        });
        jPanel3.add(pharmacyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 160, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/icons8-password-24.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 30, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/icons8-care-100.png"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInBtnActionPerformed
        // TODO add your handling code here:
        Boolean foundUser = false;
        
        if(this.applicationSystem.getUseraccountDirectory().authenticateUser(userNameField.getText(), passwordField.getText()) != null){
            UserAccount userAccount = this.applicationSystem.getUseraccountDirectory().authenticateUser(userNameField.getText(), passwordField.getText()); 
            foundUser = true;
            userAccount.getRole().createWorkArea(applicationSystem, userAccount);
            this.setVisible(false);   
        }
        
        if(!foundUser) {
            JOptionPane.showMessageDialog(null, "Invalid Credentials");
        }
        
    
                                           

    }//GEN-LAST:event_logInBtnActionPerformed

    private void hospitalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalBtnActionPerformed
        // TODO add your handling code here:
        HospitalLoginJFrame h1 = new HospitalLoginJFrame(this.applicationSystem, this.userAccount);
        h1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_hospitalBtnActionPerformed

    private void ambulanceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambulanceBtnActionPerformed
        // TODO add your handling code here:
        AmbulanceLoginJFrame a1 = new AmbulanceLoginJFrame(this.applicationSystem, this.userAccount);
        a1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ambulanceBtnActionPerformed

    private void pharmacyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pharmacyBtnActionPerformed
        // TODO add your handling code here:
        PharmacyLoginJFrame p1 = new PharmacyLoginJFrame(this.applicationSystem, this.userAccount);
        p1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pharmacyBtnActionPerformed

    private void diagnosticsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagnosticsBtnActionPerformed
        // TODO add your handling code here:
        DiagnosticsLoginJFrame d1 = new DiagnosticsLoginJFrame(this.applicationSystem, this.userAccount);
        d1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_diagnosticsBtnActionPerformed

    private void userNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ambulanceBtn;
    private javax.swing.JButton diagnosticsBtn;
    private javax.swing.JButton hospitalBtn;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton logInBtn;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton pharmacyBtn;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables
}
